// export const server: string = "localhost"
// export const server: string = "192.168.1.228"
// export const server: string = "ge-staging-vm2.eastus.cloudapp.azure.com"
export const server: string = "analystconsole.westeurope.cloudapp.azure.com"
// export const server: string = "ge-preprod.eastus.cloudapp.azure.com"